const emojiList = {
  puzzle: { icon: '🧩', unicode: '\u{1F9E9}', description: 'Widget to grid' },
  satellite: { icon: '📡', unicode: '\u{1F4E1}', description: 'Serviceworker' },
  cross: { icon: '❌', unicode: '\u{274C}', description: 'Delete widget' },
  arrowDown: { icon: '⬇', unicode: '\u{2B07}', description: 'Increase height' },
  arrowRight: { icon: '➡', unicode: '\u{27A1}', description: 'Increase width' },
  arrowUp: { icon: '⬆', unicode: '\u{2B06}', description: 'Decrease height' },
  arrowLeft: { icon: '⬅', unicode: '\u{2B05}', description: 'Decrease width' },
  magnifyingGlass: { icon: '🔍', unicode: '\u{1F50D}', description: 'Search' },
  wrench: { icon: '🔧', unicode: '\u{1F527}', description: 'Tune' },
  link: { icon: '🔗', unicode: '\u{1F517}', description: 'Link' },
  ruler: { icon: '📏', unicode: '\u{1F4CF}', description: 'Adjust widget size' },
  triangularRuler: { icon: '📐', unicode: '\u{1F4D0}', description: 'Adjust widget size' },
  toolbox: { icon: '🧰', unicode: '\u{1F9F0}', description: 'Toolbox' },
  hammerAndWrench: { icon: '🛠️', unicode: '\u{1F6E0}', description: 'Wrench' },
  compass: { icon: '🧭', unicode: '\u{1F9ED}', description: 'Compass' },
  serviceWorkerEnabled: { icon: '🌐', unicode: '\u{1F310}', description: 'Globe' },
  serviceWorkerDisabled: { icon: '🚫', unicode: '\u{1F6AB}', description: 'Prohibited' },
  pinching: { icon: '🤏', unicode: '\u{1F90F}', description: 'Drag and drop' },
  fullscreen: { icon: '▢', unicode: '\u{25A2}', description: 'Fullscreen' },
  dna: { icon: '🧬', unicode: '\u{1F9EC}', description: 'Settings' },
  gear: { icon: '⚙️', unicode: '\u{2699}', description: 'Settings' },
  locked: { icon: '🔒', unicode: '\u{1F512}', description: 'Locked (security, encryption)' },
  unlocked: { icon: '🔓', unicode: '\u{1F513}', description: 'Unlocked' },
  floppyDisk: { icon: '💾', unicode: '\u{1F4BE}', description: 'Floppy Disk (old school storage)' },
  keyboard: { icon: '⌨️', unicode: '\u{2328}', description: 'Keyboard' },
  mouse: { icon: '🖱️', unicode: '\u{1F5B1}', description: 'Mouse' },
  joystick: { icon: '🕹️', unicode: '\u{1F579}', description: 'Joystick' },
  computer: { icon: '💻', unicode: '\u{1F4BB}', description: 'Computer' },
  mobile: { icon: '📱', unicode: '\u{1F4F1}', description: 'Mobile Phone' },
  phone: { icon: '📞', unicode: '\u{1F4F2}', description: 'Phone' },
  camera: { icon: '📷', unicode: '\u{1F4F7}', description: 'Camera' },
  videoCamera: { icon: '📹', unicode: '\u{1F4F9}', description: 'Video Camera' },
  speaker: { icon: '🔊', unicode: '\u{1F50A}', description: 'Speaker' },
  shield: { icon: '🛡️', unicode: '\u{1F6E1}', description: 'Shield (protection, security)' },
  launch: { icon: '🚀', unicode: '\u{1F680}', description: 'Start a service' },
  edit: { icon: '✏️', unicode: '\u{270F}\u{FE0F}', description: 'Edit or write' }
}

export default emojiList
